### ISSUE TITLE
First thoughts on OpenDevinPowerShell

### ISSUE THREAD

**Issue by Redrum624** [risingsunomi/OpenDevinPowerShell#1]
I'm really impressed by the changes made thus far!
I think that the terminal in OpenDevin should be set as PowerShell permanently for windows users.

Here are my first thoughts and impressions:

1- Needed to change my PowerShell execution policy to "Bypass"

2- 
```
Setting up frontend
Test-Path : Cannot bind parameter because parameter 'Path' is specified more than once. To provide multiple values to
parameters that can accept multiple values, use the array syntax. For example, "-parameter value1,value2,value3".
At C:\Dev\OpenDevinPowerShell\OpenDevinWindowsInstall.ps1:131 char:56
+ if (Test-Path -Path "package-lock.json" -and Test-Path -Path "node_mo ...
+                                                        ~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Test-Path], ParameterBindingException
    + FullyQualifiedErrorId : ParameterAlreadyBound,Microsoft.PowerShell.Commands.TestPathCommand
```

3- LLM_BASE_URL is missing from config.toml

4- Terminal is not in the Workspace area (which might be a good thing, I don't know if they changed it recently)

5- WORKSPACE_DIR was empty after installation even if I supplied the right directory

6- WORKSPACE_DIR needs to be written with forward slashes instead of the Windows default back slashes, like so "C:/Dev/OpenDevinPowerShell/opendevin_env/OpenDevin/workspace"

7- My working config.toml for LM Studio:

```
LLM_MODEL="http://localhost:1234/v1/models"
LLM_BASE_URL="http://localhost:1234/v1"
LLM_API_KEY="lm-studio"
LLM_EMBEDDING_MODEL="local"
WORKSPACE_DIR="C:/Dev/OpenDevinPowerShell/opendevin_env/OpenDevin/workspace"
```

TEST 1

8- Project:
a simple webpage that says "hello world"

Creates:
hello_world.html

Terminal:
```
$ /usr/bin/python3 /workspace/hello_world.py
/usr/bin/python3: can't open file '/workspace/hello_world.py': [Errno 2] No such file or directory


$ /usr/bin/python3 hello_world.py &
/usr/bin/python3: can't open file '/workspace/hello_world.py': [Errno 2] No such file or directory
```

PowerShell:
```
==============
STEP 97

PLAN:
a simple webpage that says "hello world"

ACTION:
FileReadAction(path='/workspace/hello_world.html', action='read')

OBSERVATION:
<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n  <meta charset=\"UTF-8\" />\n</head>\n<body><script>console.log('Hello World');</script></body>\n</html>
```

The first time it wrote the HTML file was better, but it's a good example.

TEST 2

9- Tougher project to test terminal:
create a Python script that displays the math and the result for "2 + 2 =" and name the file "calcul.py"

Creates: calcul.py

Terminal:
```
$ ./calcul.py
./calcul.py: line 1: syntax error near unexpected token '"2 + 2 ="'
./calcul.py: line 1: 'print("2 + 2 =")\nprint(2+2)'
```

Worked well execept for the coding error.

Corrected it as:
```
#! /usr/bin/python
print('2 + 2 =', '4')
```

Terminal:
```
$ /usr/bin/python /workspace/calcul.py
/bin/bash: line 1: /usr/bin/python: No such file or directory


$ /usr/bin/python /workspace/calcul.py
/bin/bash: line 1: /usr/bin/python: No such file or directory

```
We are back to Bash.

So it called the file correctly at first but defaulted to "/usr/bin/python" afterwards.

A big thank you for helping the Windows community!

**Comment by risingsunomi** [comment]
Thank you for the feedback. Will dig into some of the points as I review the errors.

One thing with the workspace issue is I kept it blank for it to default to what is set in the OpenDevin/config.py as was running into Path issues using the Linux based default "./workspace". Will put a default to use windows paths.

More thoughts to come as I get started today. 

Thank you and appreciate your work on this.

**Comment by BradKML** [comment]
@risingsunomi also how is this gonna work with the new version of OpenDevin as "CodeAct"?

**Comment by risingsunomi** [comment]
> @risingsunomi also how is this gonna work with the new version of OpenDevin as "CodeAct"?

I will need to update this repo, if needed. Haven't touched it in a bit but will try to look this/next week.

**Comment by risingsunomi** [comment]
I have added updates to the install script but there is a major blocking issue with backend starting. This has to do with the OpenDevin backend.
